Fix/msg update client
terra-money/terra.js pull request #252
Opened 2022-04-07 05:01 UTC by Vritra4

parse header in MsgUpdateClient

2022-04-11 06:20 UTC, hanjukim commented
Can we add some tests?

2022-04-19 01:25 UTC, hanjukim requested changes

2022-04-19 01:25 UTC, hanjukim commented on src/core/ibc/msgs/client/MsgUpdateClient.ts
> +    console.log(JSON.stringify(header));
remove console.log

2022-04-19 11:37 UTC, Vritra4 commented
i'll add *.spec.ts also..

2022-04-20 09:14 UTC, hanjukim approved these changes

2022-04-20 09:14 UTC, hanjukim commented
LGTM

2022-04-20 09:40 UTC, merged